### ISSUE TITLE
Why are getters in ArimaCoefficients package-private?

### ISSUE THREAD

**Issue by twiechert** [signaflo/java-timeseries#6]
It would be nice to be able to inspect the ARIMA coefficients after fitting. Unfortunately, the getter methods in the above mentioned class are package-private. Is there a reason for that?

**Comment by twiechert** [comment]
Not present in the master.

**Comment by signaflo** [comment]
@twiechert, why did you close this one? I believe the getters in the master branch are package-private still. I make everything as private as possible by default, and then wait for a compelling reason to make anything public. This has annoyed me as well when playing around with it in JShell. Currently the only way to see the coefficients is through the toString method.

Right now, with the streaming ARIMA idea, I'm also considering refactoring the coefficients. It might make sense to create a coefficient object that wraps both the value and its associated standard error. The coefficients class could then store a list of these coefficient objects instead of primitive arrays. Potential performance impact is my only concern.
